const express = require('express');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const helmet = require('helmet');
const multer = require('multer');
const Stripe = require('stripe');
const { sql } = require('@vercel/postgres');
const { put } = require('@vercel/blob');

const app = express();
const APP_URL = (process.env.APP_URL || '').replace(/\/$/, '');
const SECRET = process.env.JWT_SECRET;
const COOKIE_SECURE = process.env.NODE_ENV === 'production';
const MIN_WITHDRAWAL = Number(process.env.MIN_WITHDRAWAL || 100);
const HOLD_DAYS = Number(process.env.COMMISSION_HOLD_DAYS || 7);
const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (req,f,cb)=>cb(null,/^image\/(png|jpe?g|webp)$/.test(f.mimetype)||f.mimetype==='video/mp4') });

if (!SECRET) console.warn('JWT_SECRET is not configured');

app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({limit:'1mb'}));

function cookieOptions(maxAge) { return { httpOnly:true, sameSite:'lax', secure:COOKIE_SECURE, path:'/', ...(maxAge ? {maxAge} : {}) }; }
function cookies(req){ const raw=req.headers.cookie||''; return Object.fromEntries(raw.split(';').filter(Boolean).map(x=>{const i=x.indexOf('='); return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]})); }
function token(u){ if(!SECRET) throw new Error('JWT_SECRET missing'); return jwt.sign({id:u.id,role:u.role},SECRET,{expiresIn:'7d'}); }
function auth(req,res,next){ try { const t=cookies(req).ph_token || (req.headers.authorization||'').replace(/^Bearer\s+/,''); if(!t) return res.status(401).json({error:'กรุณาเข้าสู่ระบบ'}); req.user=jwt.verify(t,SECRET); next(); } catch { return res.status(401).json({error:'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่'}); } }
function admin(req,res,next){ if(req.user.role!=='admin') return res.status(403).json({error:'ไม่มีสิทธิ์'}); next(); }
function abs(req,p){ return `${APP_URL || `${req.protocol}://${req.get('host')}`}${p}`; }
function code(){ return crypto.randomBytes(6).toString('hex').toUpperCase(); }
function orderNo(){ return 'PH'+Date.now().toString(36).toUpperCase()+crypto.randomBytes(3).toString('hex').toUpperCase(); }

let initialized;
async function init(){
  if(initialized) return initialized;
  initialized=(async()=>{
    await sql`CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'member',status TEXT NOT NULL DEFAULT 'pending',code TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS products (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT DEFAULT '',image TEXT DEFAULT '',price NUMERIC(12,2) NOT NULL DEFAULT 0,commission_rate NUMERIC(6,2) NOT NULL DEFAULT 0,stock INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS media (id BIGSERIAL PRIMARY KEY,product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,type TEXT NOT NULL,title TEXT NOT NULL,url TEXT NOT NULL,caption TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS clicks (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),product_id BIGINT NOT NULL REFERENCES products(id),visitor_id TEXT,ip_hash TEXT,user_agent TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS orders (id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),click_id BIGINT REFERENCES clicks(id),order_no TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,customer_email TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,subtotal NUMERIC(12,2) NOT NULL,shipping_fee NUMERIC(12,2) NOT NULL DEFAULT 0,total NUMERIC(12,2) NOT NULL,commission NUMERIC(12,2) NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending',payment_status TEXT NOT NULL DEFAULT 'unpaid',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS order_items (id BIGSERIAL PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),name TEXT NOT NULL,price NUMERIC(12,2) NOT NULL,qty INTEGER NOT NULL,commission_rate NUMERIC(6,2) NOT NULL,commission NUMERIC(12,2) NOT NULL)`;
    await sql`CREATE TABLE IF NOT EXISTS payments (id BIGSERIAL PRIMARY KEY,order_id BIGINT UNIQUE NOT NULL REFERENCES orders(id) ON DELETE CASCADE,provider TEXT NOT NULL,provider_payment_id TEXT,amount NUMERIC(12,2) NOT NULL,currency TEXT NOT NULL DEFAULT 'thb',status TEXT NOT NULL DEFAULT 'pending',checkout_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS webhook_events (id BIGSERIAL PRIMARY KEY,provider TEXT NOT NULL,event_id TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS wallets (id BIGSERIAL PRIMARY KEY,user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,available NUMERIC(12,2) NOT NULL DEFAULT 0,pending NUMERIC(12,2) NOT NULL DEFAULT 0,paid NUMERIC(12,2) NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS wallet_transactions (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),type TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL,reference TEXT,description TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS withdrawals (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),amount NUMERIC(12,2) NOT NULL,method TEXT NOT NULL,account_name TEXT NOT NULL,account_number TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),processed_at TIMESTAMPTZ)`;
    const a=await sql`SELECT id FROM users WHERE email='admin@promohub.local'`;

    if(a.rows.length===0 && false){const hash=await bcrypt.hash(process.env.DEFAULT_ADMIN_PASSWORD || crypto.randomBytes(18).toString('base64url'),12); await sql`INSERT INTO users(name,email,password,role,status,code) VALUES('PROMO HUB Admin','admin@promohub.local',${hash},'admin','approved',${code()})`;}
    const p=await sql`SELECT COUNT(*)::int AS c FROM products`;
    if(!p.rows[0].c){await sql`INSERT INTO products(name,description,price,commission_rate,stock) VALUES('Blackmores Bio Magnesium Advanced + D3','แมกนีเซียม + D3 สำหรับดูแลสุขภาพ',850,10,100),('Blackmores Fish Oil 1000','น้ำมันปลา',650,10,100),('Blackmores Vitamin C 1000','วิตามินซี',590,8,100)`;}
  })().catch(e=>{initialized=null; throw e});
  return initialized;
}

app.use(async (req,res,next)=>{ try { await init(); next(); } catch(e){ console.error(e); res.status(500).json({error:'Database is not configured or unavailable',detail:process.env.NODE_ENV==='production'?undefined:e.message}); }});

app.post('/api/register',async(req,res)=>{const {name,email,password}=req.body||{}; if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email||''))||String(password||'').length<8)return res.status(400).json({error:'กรุณากรอกชื่อ อีเมล และรหัสผ่านอย่างน้อย 8 ตัวอักษร'}); try{const hash=await bcrypt.hash(password,12);const c=code();await sql`INSERT INTO users(name,email,password,code) VALUES(${String(name).trim()},${String(email).trim().toLowerCase()},${hash},${c})`;res.json({ok:true,message:'สมัครสมาชิกสำเร็จ รอผู้ดูแลอนุมัติ'});}catch(e){res.status(400).json({error:'อีเมลนี้ถูกใช้แล้วหรือสมัครสมาชิกไม่สำเร็จ'});}});
app.post('/api/login',async(req,res)=>{const {email,password}=req.body||{};const r=await sql`SELECT * FROM users WHERE email=${String(email||'').trim().toLowerCase()}`;const u=r.rows[0];if(!u||!(await bcrypt.compare(String(password||''),u.password)))return res.status(401).json({error:'อีเมลหรือรหัสผ่านไม่ถูกต้อง'});if(u.status==='suspended')return res.status(403).json({error:'บัญชีถูกระงับ'});res.cookie('ph_token',token(u),cookieOptions(7*24*60*60*1000));res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role,status:u.status,code:u.code,created_at:u.created_at}});});
app.post('/api/logout',(req,res)=>{res.clearCookie('ph_token',cookieOptions());res.json({ok:true});});
app.get('/api/me',auth,async(req,res)=>{const r=await sql`SELECT id,name,email,role,status,code,created_at FROM users WHERE id=${req.user.id}`;res.json(r.rows[0]);});

app.get('/api/products',auth,async(req,res)=>{const r=await sql`SELECT id,name,description,image,price,commission_rate,stock FROM products WHERE active=true ORDER BY id DESC`;res.json(r.rows);});
app.get('/api/products/:id',auth,async(req,res)=>{const p=await sql`SELECT id,name,description,image,price,commission_rate,stock FROM products WHERE id=${Number(req.params.id)} AND active=true`;if(!p.rows[0])return res.status(404).json({error:'ไม่พบสินค้า'});const m=await sql`SELECT id,type,title,url,caption FROM media WHERE product_id=${Number(req.params.id)} ORDER BY id DESC`;res.json({...p.rows[0],media:m.rows});});
app.get('/api/products/:id/media',auth,async(req,res)=>{const r=await sql`SELECT id,type,title,url,caption FROM media WHERE product_id=${Number(req.params.id)} ORDER BY id DESC`;res.json(r.rows);});

app.get('/api/clicks',auth,async(req,res)=>{const p=await sql`SELECT id FROM products WHERE id=${Number(req.query.productId)} AND active=true`;if(!p.rows[0])return res.status(404).json({error:'ไม่พบสินค้า'});const c=await sql`INSERT INTO clicks(user_id,product_id,visitor_id) VALUES(${req.user.id},${p.rows[0].id},${crypto.randomUUID()}) RETURNING id`;const u=await sql`SELECT code FROM users WHERE id=${req.user.id}`;res.json({clickId:c.rows[0].id,link:abs(req,`/r/${u.rows[0].code}/${p.rows[0].id}`)});});
app.get('/r/:code/:productId',async(req,res)=>{const u=await sql`SELECT id,code,status FROM users WHERE code=${req.params.code} AND role='member'`;const p=await sql`SELECT id FROM products WHERE id=${Number(req.params.productId)} AND active=true`;if(!u.rows[0]||u.rows[0].status!=='approved'||!p.rows[0])return res.redirect('/?ref=invalid');const ipHash=crypto.createHash('sha256').update(`${req.ip||''}${SECRET||''}`).digest('hex');const c=await sql`INSERT INTO clicks(user_id,product_id,visitor_id,ip_hash,user_agent) VALUES(${u.rows[0].id},${p.rows[0].id},${crypto.randomUUID()},${ipHash},${req.get('user-agent')||''}) RETURNING id`;res.cookie('ph_click',String(c.rows[0].id),{httpOnly:true,sameSite:'lax',secure:COOKIE_SECURE,maxAge:30*86400000,path:'/'});res.redirect(`/shop.html?product=${encodeURIComponent(p.rows[0].id)}`);});

app.post('/api/public/orders',async(req,res)=>{const {items,customer}=req.body||{};if(!Array.isArray(items)||!items.length||!customer?.name||!customer?.email||!customer?.phone||!customer?.address)return res.status(400).json({error:'ข้อมูล Checkout ไม่ครบ'});const clean=[];for(const x of items){const r=await sql`SELECT * FROM products WHERE id=${Number(x.productId)} AND active=true`;const p=r.rows[0];const qty=Math.max(1,Math.min(99,Number(x.qty)||1));if(!p||p.stock>0&&qty>p.stock)return res.status(400).json({error:'มีสินค้าที่ไม่พร้อมขายหรือจำนวนไม่พอ'});clean.push({p,qty});}const subtotal=clean.reduce((s,x)=>s+Number(x.p.price)*x.qty,0);const shipping=subtotal>=1000?0:50;const total=subtotal+shipping;const ck=cookies(req).ph_click;const cr=ck?await sql`SELECT c.*,u.status FROM clicks c JOIN users u ON u.id=c.user_id WHERE c.id=${Number(ck)}`:{rows:[]};const click=cr.rows[0]&&cr.rows[0].status==='approved'?cr.rows[0]:null;const commission=click?clean.filter(x=>Number(x.p.id)===Number(click.product_id)).reduce((s,x)=>s+Number(x.p.price)*x.qty*Number(x.p.commission_rate)/100,0):0;const o=await sql`INSERT INTO orders(user_id,click_id,order_no,customer_name,customer_email,phone,address,subtotal,shipping_fee,total,commission) VALUES(${click?.user_id||null},${click?.id||null},${orderNo()},${String(customer.name).trim()},${String(customer.email).trim().toLowerCase()},${String(customer.phone).trim()},${String(customer.address).trim()},${subtotal},${shipping},${total},${commission}) RETURNING id,order_no`;const orderId=o.rows[0].id;for(const x of clean){await sql`INSERT INTO order_items(order_id,product_id,name,price,qty,commission_rate,commission) VALUES(${orderId},${x.p.id},${x.p.name},${x.p.price},${x.qty},${x.p.commission_rate},${Number(x.p.id)===Number(click?.product_id)?Number(x.p.price)*x.qty*Number(x.p.commission_rate)/100:0})`;}
let pay={provider:'sandbox',status:'pending',checkoutUrl:abs(req,`/sandbox-pay.html?order=${orderId}`)};if(stripe){try{const session=await stripe.checkout.sessions.create({mode:'payment',customer_email:customer.email,line_items:clean.map(x=>({price_data:{currency:'thb',product_data:{name:x.p.name},unit_amount:Math.round(Number(x.p.price)*100)},quantity:x.qty})),success_url:`${APP_URL}/payment-success.html?order=${orderId}&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${APP_URL}/shop.html?cancelled=1`,metadata:{orderId:String(orderId)}});pay={provider:'stripe',status:'pending',checkoutUrl:session.url,providerPaymentId:session.id};}catch(e){console.error(e);return res.status(500).json({error:'สร้างหน้าชำระเงินไม่สำเร็จ'});}}
await sql`INSERT INTO payments(order_id,provider,provider_payment_id,amount,status,checkout_url) VALUES(${orderId},${pay.provider},${pay.providerPaymentId||null},${total},'pending',${pay.checkoutUrl})`;res.clearCookie('ph_click',{httpOnly:true,sameSite:'lax',secure:COOKIE_SECURE,path:'/'});res.json({ok:true,orderId,orderNo:o.rows[0].order_no,total,payment:pay});});

async function settle(orderId,paymentId){const o=await sql`SELECT * FROM orders WHERE id=${Number(orderId)}`;if(!o.rows[0]||o.rows[0].payment_status==='paid')return;await sql`UPDATE orders SET payment_status='paid',status='confirmed' WHERE id=${Number(orderId)}`;await sql`UPDATE payments SET status='paid',provider_payment_id=COALESCE(provider_payment_id,${paymentId}) WHERE order_id=${Number(orderId)}`;if(o.rows[0].user_id&&Number(o.rows[0].commission)>0){await sql`INSERT INTO wallets(user_id) VALUES(${o.rows[0].user_id}) ON CONFLICT(user_id) DO NOTHING`;await sql`UPDATE wallets SET pending=pending+${o.rows[0].commission},updated_at=NOW() WHERE user_id=${o.rows[0].user_id}`;await sql`INSERT INTO wallet_transactions(user_id,type,amount,reference,description) VALUES(${o.rows[0].user_id},'commission_pending',${o.rows[0].commission},${o.rows[0].order_no},'คอมมิชชันรอการยืนยัน')`;}}
app.post('/api/webhooks/stripe',express.raw({type:'application/json'}),async(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Stripe webhook is not configured');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);}catch(e){return res.status(400).send(`Webhook Error: ${e.message}`);}const x=await sql`SELECT id FROM webhook_events WHERE event_id=${event.id}`;if(x.rows.length)return res.json({received:true,duplicate:true});await sql`INSERT INTO webhook_events(provider,event_id) VALUES('stripe',${event.id})`;if(event.type==='checkout.session.completed')await settle(Number(event.data.object.metadata?.orderId),event.data.object.id);return res.json({received:true});});

app.get('/api/dashboard',auth,async(req,res)=>{const c=await sql`SELECT COUNT(*)::int c FROM clicks WHERE user_id=${req.user.id}`;const o=await sql`SELECT COUNT(*)::int c,COALESCE(SUM(total),0) sales,COALESCE(SUM(commission),0) commission FROM orders WHERE user_id=${req.user.id} AND payment_status='paid'`;const w=await sql`SELECT available,pending,paid FROM wallets WHERE user_id=${req.user.id}`;res.json({clicks:c.rows[0].c,orders:o.rows[0].c,sales:Number(o.rows[0].sales),commissionAvailable:Number(w.rows[0]?.available||0),commissionPending:Number(w.rows[0]?.pending||0),paid:Number(w.rows[0]?.paid||0)});});
app.get('/api/orders',auth,async(req,res)=>{const r=await sql`SELECT order_no,customer_name,total,commission,status,payment_status,created_at FROM orders WHERE user_id=${req.user.id} ORDER BY id DESC`;res.json(r.rows);});
app.get('/api/links',auth,async(req,res)=>{const u=await sql`SELECT code FROM users WHERE id=${req.user.id}`;const r=await sql`SELECT p.id,p.name,p.image,p.price,p.commission_rate,COUNT(c.id)::int clicks FROM products p LEFT JOIN clicks c ON c.product_id=p.id AND c.user_id=${req.user.id} WHERE p.active=true GROUP BY p.id ORDER BY p.id DESC`;res.json(r.rows.map(x=>({...x,link:abs(req,`/r/${u.rows[0].code}/${x.id}`)})));});
app.get('/api/wallet',auth,async(req,res)=>{await sql`INSERT INTO wallets(user_id) VALUES(${req.user.id}) ON CONFLICT(user_id) DO NOTHING`;const w=await sql`SELECT * FROM wallets WHERE user_id=${req.user.id}`;const t=await sql`SELECT type,amount,reference,description,created_at FROM wallet_transactions WHERE user_id=${req.user.id} ORDER BY id DESC LIMIT 100`;const wd=await sql`SELECT id,amount,method,account_name,account_number,status,note,created_at,processed_at FROM withdrawals WHERE user_id=${req.user.id} ORDER BY id DESC LIMIT 50`;res.json({wallet:w.rows[0],transactions:t.rows,withdrawals:wd.rows});});
app.post('/api/withdrawals',auth,async(req,res)=>{const {amount,method,accountName,accountNumber}=req.body||{};const n=Number(amount);if(!Number.isFinite(n)||n<MIN_WITHDRAWAL)return res.status(400).json({error:`ยอดถอนขั้นต่ำ ${MIN_WITHDRAWAL.toLocaleString()} บาท`});await sql`INSERT INTO wallets(user_id) VALUES(${req.user.id}) ON CONFLICT(user_id) DO NOTHING`;const w=await sql`SELECT available FROM wallets WHERE user_id=${req.user.id}`;if(Number(w.rows[0].available)<n)return res.status(400).json({error:'ยอดคงเหลือไม่พอ'});const r=await sql`INSERT INTO withdrawals(user_id,amount,method,account_name,account_number) VALUES(${req.user.id},${n},${method},${String(accountName).trim()},${String(accountNumber).trim()}) RETURNING id`;await sql`UPDATE wallets SET available=available-${n},updated_at=NOW() WHERE user_id=${req.user.id}`;await sql`INSERT INTO wallet_transactions(user_id,type,amount,reference,description) VALUES(${req.user.id},'withdrawal',${-n},${`WD-${r.rows[0].id}`},'ขอถอนเงิน')`;res.json({ok:true,id:r.rows[0].id});});

app.get('/api/admin/stats',auth,admin,async(req,res)=>{const a=await sql`SELECT COUNT(*) FILTER(WHERE role='member')::int users,COUNT(*) FILTER(WHERE role='member' AND status='pending')::int pending_users FROM users`;const b=await sql`SELECT COUNT(*) FILTER(WHERE payment_status='paid')::int orders,COALESCE(SUM(total) FILTER(WHERE payment_status='paid'),0) sales,COALESCE(SUM(commission) FILTER(WHERE payment_status='paid'),0) commission FROM orders`;const w=await sql`SELECT COUNT(*)::int withdrawals FROM withdrawals WHERE status='pending'`;res.json({users:a.rows[0].users,pendingUsers:a.rows[0].pending_users,orders:b.rows[0].orders,sales:Number(b.rows[0].sales),commission:Number(b.rows[0].commission),withdrawals:w.rows[0].withdrawals});});
app.get('/api/admin/users',auth,admin,async(req,res)=>res.json((await sql`SELECT id,name,email,status,code,created_at FROM users WHERE role='member' ORDER BY id DESC`).rows));
app.patch('/api/admin/users/:id/status',auth,admin,async(req,res)=>{if(!['pending','approved','suspended'].includes(req.body?.status))return res.status(400).json({error:'สถานะไม่ถูกต้อง'});await sql`UPDATE users SET status=${req.body.status} WHERE id=${Number(req.params.id)} AND role='member'`;res.json({ok:true});});
app.get('/api/admin/orders',auth,admin,async(req,res)=>res.json((await sql`SELECT o.id,o.order_no,o.customer_name,o.customer_email,o.total,o.commission,o.status,o.payment_status,o.created_at,u.name member FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 500`).rows));
app.patch('/api/admin/orders/:id/status',auth,admin,async(req,res)=>{if(!['pending','confirmed','cancelled','shipped','completed'].includes(req.body?.status))return res.status(400).json({error:'สถานะไม่ถูกต้อง'});await sql`UPDATE orders SET status=${req.body.status} WHERE id=${Number(req.params.id)}`;res.json({ok:true});});
app.get('/api/admin/products',auth,admin,async(req,res)=>res.json((await sql`SELECT * FROM products ORDER BY id DESC`).rows));
app.post('/api/admin/products',auth,admin,async(req,res)=>{const x=req.body||{};if(!x.name||Number(x.price)<0||Number(x.commissionRate)<0)return res.status(400).json({error:'ข้อมูลสินค้าไม่ถูกต้อง'});const r=await sql`INSERT INTO products(name,description,image,price,commission_rate,stock) VALUES(${String(x.name).trim()},${x.description||''},${x.image||''},${Number(x.price)},${Number(x.commissionRate)},${Number(x.stock)||0}) RETURNING id`;res.json({id:r.rows[0].id});});
app.patch('/api/admin/products/:id',auth,admin,async(req,res)=>{const x=req.body||{};await sql`UPDATE products SET name=COALESCE(${x.name??null},name),description=COALESCE(${x.description??null},description),image=COALESCE(${x.image??null},image),price=COALESCE(${x.price==null?null:Number(x.price)},price),commission_rate=COALESCE(${x.commissionRate==null?null:Number(x.commissionRate)},commission_rate),stock=COALESCE(${x.stock==null?null:Number(x.stock)},stock),active=COALESCE(${x.active==null?null:Boolean(x.active)},active) WHERE id=${Number(req.params.id)}`;res.json({ok:true});});
app.post('/api/admin/media',auth,admin,async(req,res)=>{const x=req.body||{};if(!x.productId||!x.type||!x.title||!x.url)return res.status(400).json({error:'ข้อมูลสื่อไม่ครบ'});const r=await sql`INSERT INTO media(product_id,type,title,url,caption) VALUES(${Number(x.productId)},${x.type},${x.title},${x.url},${x.caption||''}) RETURNING id`;res.json({id:r.rows[0].id});});
app.delete('/api/admin/media/:id',auth,admin,async(req,res)=>{await sql`DELETE FROM media WHERE id=${Number(req.params.id)}`;res.json({ok:true});});
app.get('/api/admin/withdrawals',auth,admin,async(req,res)=>res.json((await sql`SELECT w.*,u.name member,u.email FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC`).rows));
app.patch('/api/admin/withdrawals/:id/status',auth,admin,async(req,res)=>{const s=req.body?.status;if(!['pending','processing','paid','rejected'].includes(s))return res.status(400).json({error:'สถานะไม่ถูกต้อง'});const w=(await sql`SELECT * FROM withdrawals WHERE id=${Number(req.params.id)}`).rows[0];if(!w)return res.status(404).json({error:'ไม่พบรายการ'});if(s==='paid'&&w.status!=='paid')await sql`UPDATE wallets SET paid=paid+${w.amount},updated_at=NOW() WHERE user_id=${w.user_id}`;if(s==='rejected'&&w.status!=='rejected'){await sql`UPDATE wallets SET available=available+${w.amount},updated_at=NOW() WHERE user_id=${w.user_id}`;await sql`INSERT INTO wallet_transactions(user_id,type,amount,reference,description) VALUES(${w.user_id},'withdrawal_refund',${w.amount},${`WD-${w.id}`},'คืนยอดจากคำขอถอนที่ถูกปฏิเสธ')`;}await sql`UPDATE withdrawals SET status=${s},processed_at=CASE WHEN ${s} IN ('paid','rejected') THEN NOW() ELSE processed_at END WHERE id=${w.id}`;res.json({ok:true});});
app.post('/api/admin/upload',auth,admin,upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'ไม่พบไฟล์หรือชนิดไฟล์ไม่รองรับ'});if(!process.env.BLOB_READ_WRITE_TOKEN)return res.status(503).json({error:'ยังไม่ได้ตั้ง BLOB_READ_WRITE_TOKEN'});const ext=(req.file.originalname.match(/\.[^.]+$/)||[''])[0].toLowerCase();const blob=await put(`promo-hub/${Date.now()}-${crypto.randomBytes(4).toString('hex')}${ext}`,req.file.buffer,{access:'public',contentType:req.file.mimetype,addRandomSuffix:false});res.json({url:blob.url,type:req.file.mimetype.startsWith('video')?'video':'image'});});

app.get('/api/health',async(req,res)=>res.json({ok:true,service:'promo-hub',database:'postgres',time:new Date().toISOString()}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'เกิดข้อผิดพลาดในเซิร์ฟเวอร์'});});

module.exports = app;
